### ISSUE TITLE
Custom link text

### ISSUE THREAD

**Issue by opcode0x** [ali-saleem/anchorme.js#52]
Is custom link text supported?

**Comment by danielsarin** [comment]
Furthermore, I would like `defaultProtocol` only to be applied to the href and not the text itself. Is this possible?

**Comment by alexcorvi** [comment]
@appbak3r 
The 2.0 release introduces two new functionalities:
- You can use the [`extensions`](http://alexcorvi.github.io/anchorme.js/#extending) for custom tokenization and lookup and thus custom transformation. a usage example of this would be supporting hashtags and mentions
- You can use [`specialTransformation`](http://alexcorvi.github.io/anchorme.js/#special-transformation) option to transform specific links (defined by a user supplied regex) in a different way, a usage example of this would be transforming images to `<img/>` tags or `<iframe/>` tags.

@danielsarin
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
